# Generated by Django 2.0.13 on 2022-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.TextField(blank=True, verbose_name='Описание')),
                ('main', models.BooleanField(verbose_name='Главное меню')),
                ('add', models.BooleanField(verbose_name='Доп. меню')),
                ('sub_categories', models.ManyToManyField(blank=True, related_name='_category_sub_categories_+', to='main.Category')),
            ],
            options={
                'verbose_name': 'Карегория',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('post', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ManyToManyField(to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('post', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='slider/grid/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки под слайдером',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('post', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2, verbose_name='День недели')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='С')),
                ('time2', models.TimeField(blank=True, null=True, verbose_name='До')),
                ('weekend', models.BooleanField(verbose_name='Выходной')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'День недели',
                'verbose_name_plural': 'График работы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('post', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Сourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('post', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
