# Generated by Django 2.0.13 on 2022-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220425_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.AlterField(
            model_name='grid',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='slider/grid/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Изображение'),
        ),
    ]
