# Generated by Django 2.0.13 on 2022-04-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220425_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentBlock',
            new_name='Payment',
        ),
    ]
