# Generated by Django 2.0.13 on 2022-04-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220426_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сourses',
            old_name='blog_views',
            new_name='c_views',
        ),
    ]
